# Generated by Django 3.2.7 on 2021-09-23 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_beneficiario', models.CharField(max_length=200)),
                ('cpf_beneficiario', models.CharField(max_length=200)),
                ('nis', models.CharField(max_length=200)),
                ('resposnsavel', models.CharField(max_length=200)),
                ('cpf_responsavel', models.CharField(max_length=200)),
                ('nis_responsavel', models.CharField(max_length=200)),
                ('enquadramento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=200)),
                ('codigo_municipio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.CharField(max_length=200)),
                ('mes', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
                ('observacao', models.CharField(max_length=200)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.beneficiario')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.endereco'),
        ),
    ]
