# Generated by Django 3.2.7 on 2021-10-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiarioAuxilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_beneficiario', models.CharField(max_length=100)),
                ('cpf_beneficiario', models.CharField(max_length=14)),
                ('nis', models.CharField(max_length=20, null=True)),
                ('responsavel', models.CharField(max_length=100, null=True)),
                ('cpf_responsavel', models.CharField(max_length=14, null=True)),
                ('nis_responsavel', models.CharField(max_length=100, null=True)),
                ('enquadramento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=200, null=True, unique=True)),
                ('codigo_municipio', models.IntegerField(null=True, unique=True)),
                ('codigo_siafi', models.IntegerField(null=True, unique=True)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.CharField(max_length=4)),
                ('mes', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacao', models.CharField(max_length=200, null=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.beneficiarioauxilio')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiarioBolsaFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(max_length=6)),
                ('mes_competencia', models.CharField(max_length=6)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('nis', models.CharField(max_length=20)),
                ('nome_favorecido', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiarioauxilio',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.endereco'),
        ),
    ]
